/**
 * Cyrillic Script Keyboard Layouts
 * Covers: Russian, Ukrainian, Bulgarian, Serbian, Belarusian, Kazakh, etc.
 */

import { KeyboardLayout, KeyDefinition } from '../types';

// ===================== RUSSIAN =====================
const russianRow1: KeyDefinition[] = [
  { key: 'й', shift: 'Й' },
  { key: 'ц', shift: 'Ц' },
  { key: 'у', shift: 'У' },
  { key: 'к', shift: 'К' },
  { key: 'е', shift: 'Е' },
  { key: 'н', shift: 'Н' },
  { key: 'г', shift: 'Г' },
  { key: 'ш', shift: 'Ш' },
  { key: 'щ', shift: 'Щ' },
  { key: 'з', shift: 'З' },
  { key: 'х', shift: 'Х' },
];

const russianRow2: KeyDefinition[] = [
  { key: 'ф', shift: 'Ф' },
  { key: 'ы', shift: 'Ы' },
  { key: 'в', shift: 'В' },
  { key: 'а', shift: 'А' },
  { key: 'п', shift: 'П' },
  { key: 'р', shift: 'Р' },
  { key: 'о', shift: 'О' },
  { key: 'л', shift: 'Л' },
  { key: 'д', shift: 'Д' },
  { key: 'ж', shift: 'Ж' },
  { key: 'э', shift: 'Э' },
];

const russianRow3: KeyDefinition[] = [
  { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
  { key: 'я', shift: 'Я' },
  { key: 'ч', shift: 'Ч' },
  { key: 'с', shift: 'С' },
  { key: 'м', shift: 'М' },
  { key: 'и', shift: 'И' },
  { key: 'т', shift: 'Т' },
  { key: 'ь', shift: 'Ь' },
  { key: 'б', shift: 'Б' },
  { key: 'ю', shift: 'Ю' },
  { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
];

const russianRow4: KeyDefinition[] = [
  { key: 'ъ', shift: 'Ъ' },
  { key: 'ё', shift: 'Ё' },
];

const russianRow5: KeyDefinition[] = [
  { key: '123', type: 'modifier', width: 1.25, label: '123' },
  { key: '🌐', type: 'modifier', width: 1, label: 'Lang' },
  { key: ' ', type: 'space', width: 5, label: 'Space' },
  { key: '.', shift: ',' },
  { key: '↵', type: 'action', width: 1.75, label: 'Return' },
];

export const russianLayout: KeyboardLayout = {
  id: 'ru',
  name: 'Russian',
  nativeName: 'Русский',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: russianRow1 },
    { keys: russianRow2 },
    { keys: russianRow3 },
    { keys: russianRow4 },
    { keys: russianRow5 },
  ],
};

// ===================== UKRAINIAN =====================
export const ukrainianLayout: KeyboardLayout = {
  id: 'uk',
  name: 'Ukrainian',
  nativeName: 'Українська',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: [
      { key: 'й', shift: 'Й' },
      { key: 'ц', shift: 'Ц' },
      { key: 'у', shift: 'У' },
      { key: 'к', shift: 'К' },
      { key: 'е', shift: 'Е' },
      { key: 'н', shift: 'Н' },
      { key: 'г', shift: 'Г' },
      { key: 'ш', shift: 'Ш' },
      { key: 'щ', shift: 'Щ' },
      { key: 'з', shift: 'З' },
      { key: 'х', shift: 'Х' },
    ]},
    { keys: [
      { key: 'ф', shift: 'Ф' },
      { key: 'і', shift: 'І' },
      { key: 'в', shift: 'В' },
      { key: 'а', shift: 'А' },
      { key: 'п', shift: 'П' },
      { key: 'р', shift: 'Р' },
      { key: 'о', shift: 'О' },
      { key: 'л', shift: 'Л' },
      { key: 'д', shift: 'Д' },
      { key: 'ж', shift: 'Ж' },
      { key: 'є', shift: 'Є' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'я', shift: 'Я' },
      { key: 'ч', shift: 'Ч' },
      { key: 'с', shift: 'С' },
      { key: 'м', shift: 'М' },
      { key: 'и', shift: 'И' },
      { key: 'т', shift: 'Т' },
      { key: 'ь', shift: 'Ь' },
      { key: 'б', shift: 'Б' },
      { key: 'ю', shift: 'Ю' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: [
      { key: 'ї', shift: 'Ї' },
      { key: 'ґ', shift: 'Ґ' },
      { key: "'", shift: '"' },
    ]},
    { keys: russianRow5 },
  ],
};

// ===================== BELARUSIAN =====================
export const belarusianLayout: KeyboardLayout = {
  id: 'be',
  name: 'Belarusian',
  nativeName: 'Беларуская',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: russianRow1 },
    { keys: [
      { key: 'ф', shift: 'Ф' },
      { key: 'ы', shift: 'Ы' },
      { key: 'в', shift: 'В' },
      { key: 'а', shift: 'А' },
      { key: 'п', shift: 'П' },
      { key: 'р', shift: 'Р' },
      { key: 'о', shift: 'О' },
      { key: 'л', shift: 'Л' },
      { key: 'д', shift: 'Д' },
      { key: 'ж', shift: 'Ж' },
      { key: 'э', shift: 'Э' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'я', shift: 'Я' },
      { key: 'ч', shift: 'Ч' },
      { key: 'с', shift: 'С' },
      { key: 'м', shift: 'М' },
      { key: 'і', shift: 'І' },
      { key: 'т', shift: 'Т' },
      { key: 'ь', shift: 'Ь' },
      { key: 'б', shift: 'Б' },
      { key: 'ю', shift: 'Ю' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: [
      { key: 'ў', shift: 'Ў' },
    ]},
    { keys: russianRow5 },
  ],
};

// ===================== BULGARIAN =====================
export const bulgarianLayout: KeyboardLayout = {
  id: 'bg',
  name: 'Bulgarian',
  nativeName: 'Български',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: [
      { key: 'у', shift: 'У' },
      { key: 'е', shift: 'Е' },
      { key: 'и', shift: 'И' },
      { key: 'ш', shift: 'Ш' },
      { key: 'щ', shift: 'Щ' },
      { key: 'к', shift: 'К' },
      { key: 'с', shift: 'С' },
      { key: 'д', shift: 'Д' },
      { key: 'з', shift: 'З' },
      { key: 'ц', shift: 'Ц' },
    ]},
    { keys: [
      { key: 'ь', shift: 'Ь' },
      { key: 'я', shift: 'Я' },
      { key: 'а', shift: 'А' },
      { key: 'о', shift: 'О' },
      { key: 'ж', shift: 'Ж' },
      { key: 'г', shift: 'Г' },
      { key: 'т', shift: 'Т' },
      { key: 'н', shift: 'Н' },
      { key: 'в', shift: 'В' },
      { key: 'м', shift: 'М' },
      { key: 'ч', shift: 'Ч' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'ю', shift: 'Ю' },
      { key: 'й', shift: 'Й' },
      { key: 'ъ', shift: 'Ъ' },
      { key: 'э', shift: 'Э' },
      { key: 'ф', shift: 'Ф' },
      { key: 'х', shift: 'Х' },
      { key: 'п', shift: 'П' },
      { key: 'р', shift: 'Р' },
      { key: 'л', shift: 'Л' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: russianRow5 },
  ],
};

// ===================== SERBIAN (CYRILLIC) =====================
export const serbianLayout: KeyboardLayout = {
  id: 'sr',
  name: 'Serbian',
  nativeName: 'Српски',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: [
      { key: 'љ', shift: 'Љ' },
      { key: 'њ', shift: 'Њ' },
      { key: 'е', shift: 'Е' },
      { key: 'р', shift: 'Р' },
      { key: 'т', shift: 'Т' },
      { key: 'з', shift: 'З' },
      { key: 'у', shift: 'У' },
      { key: 'и', shift: 'И' },
      { key: 'о', shift: 'О' },
      { key: 'п', shift: 'П' },
      { key: 'ш', shift: 'Ш' },
    ]},
    { keys: [
      { key: 'а', shift: 'А' },
      { key: 'с', shift: 'С' },
      { key: 'д', shift: 'Д' },
      { key: 'ф', shift: 'Ф' },
      { key: 'г', shift: 'Г' },
      { key: 'х', shift: 'Х' },
      { key: 'ј', shift: 'Ј' },
      { key: 'к', shift: 'К' },
      { key: 'л', shift: 'Л' },
      { key: 'ч', shift: 'Ч' },
      { key: 'ћ', shift: 'Ћ' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'ђ', shift: 'Ђ' },
      { key: 'ц', shift: 'Ц' },
      { key: 'в', shift: 'В' },
      { key: 'б', shift: 'Б' },
      { key: 'н', shift: 'Н' },
      { key: 'м', shift: 'М' },
      { key: 'ж', shift: 'Ж' },
      { key: 'џ', shift: 'Џ' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: russianRow5 },
  ],
};

// ===================== KAZAKH =====================
export const kazakhLayout: KeyboardLayout = {
  id: 'kk',
  name: 'Kazakh',
  nativeName: 'Қазақша',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: [
      { key: 'й', shift: 'Й' },
      { key: 'ц', shift: 'Ц' },
      { key: 'у', shift: 'У' },
      { key: 'к', shift: 'К' },
      { key: 'е', shift: 'Е' },
      { key: 'н', shift: 'Н' },
      { key: 'г', shift: 'Г' },
      { key: 'ш', shift: 'Ш' },
      { key: 'щ', shift: 'Щ' },
      { key: 'з', shift: 'З' },
      { key: 'х', shift: 'Х' },
    ]},
    { keys: [
      { key: 'ф', shift: 'Ф' },
      { key: 'ы', shift: 'Ы' },
      { key: 'в', shift: 'В' },
      { key: 'а', shift: 'А' },
      { key: 'п', shift: 'П' },
      { key: 'р', shift: 'Р' },
      { key: 'о', shift: 'О' },
      { key: 'л', shift: 'Л' },
      { key: 'д', shift: 'Д' },
      { key: 'ж', shift: 'Ж' },
      { key: 'э', shift: 'Э' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'я', shift: 'Я' },
      { key: 'ч', shift: 'Ч' },
      { key: 'с', shift: 'С' },
      { key: 'м', shift: 'М' },
      { key: 'и', shift: 'И' },
      { key: 'т', shift: 'Т' },
      { key: 'ь', shift: 'Ь' },
      { key: 'б', shift: 'Б' },
      { key: 'ю', shift: 'Ю' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: [
      { key: 'ә', shift: 'Ә' },
      { key: 'і', shift: 'І' },
      { key: 'ң', shift: 'Ң' },
      { key: 'ғ', shift: 'Ғ' },
      { key: 'ү', shift: 'Ү' },
      { key: 'ұ', shift: 'Ұ' },
      { key: 'қ', shift: 'Қ' },
      { key: 'ө', shift: 'Ө' },
      { key: 'һ', shift: 'Һ' },
    ]},
    { keys: russianRow5 },
  ],
};

// ===================== MACEDONIAN =====================
export const macedonianLayout: KeyboardLayout = {
  id: 'mk',
  name: 'Macedonian',
  nativeName: 'Македонски',
  script: 'cyrillic',
  direction: 'ltr',
  hasShift: true,
  rows: [
    { keys: [
      { key: 'љ', shift: 'Љ' },
      { key: 'њ', shift: 'Њ' },
      { key: 'е', shift: 'Е' },
      { key: 'р', shift: 'Р' },
      { key: 'т', shift: 'Т' },
      { key: 'ѕ', shift: 'Ѕ' },
      { key: 'у', shift: 'У' },
      { key: 'и', shift: 'И' },
      { key: 'о', shift: 'О' },
      { key: 'п', shift: 'П' },
      { key: 'ш', shift: 'Ш' },
    ]},
    { keys: [
      { key: 'а', shift: 'А' },
      { key: 'с', shift: 'С' },
      { key: 'д', shift: 'Д' },
      { key: 'ф', shift: 'Ф' },
      { key: 'г', shift: 'Г' },
      { key: 'х', shift: 'Х' },
      { key: 'ј', shift: 'Ј' },
      { key: 'к', shift: 'К' },
      { key: 'л', shift: 'Л' },
      { key: 'ч', shift: 'Ч' },
      { key: 'ќ', shift: 'Ќ' },
    ]},
    { keys: [
      { key: '⇧', type: 'modifier', width: 1.5, label: 'Shift' },
      { key: 'ѓ', shift: 'Ѓ' },
      { key: 'ц', shift: 'Ц' },
      { key: 'в', shift: 'В' },
      { key: 'б', shift: 'Б' },
      { key: 'н', shift: 'Н' },
      { key: 'м', shift: 'М' },
      { key: 'ж', shift: 'Ж' },
      { key: 'џ', shift: 'Џ' },
      { key: '⌫', type: 'action', width: 1.5, label: 'Delete' },
    ]},
    { keys: russianRow5 },
  ],
};

export const cyrillicLayouts = {
  ru: russianLayout,
  uk: ukrainianLayout,
  be: belarusianLayout,
  bg: bulgarianLayout,
  sr: serbianLayout,
  kk: kazakhLayout,
  mk: macedonianLayout,
};
